-- ============================================
-- COMPREHENSIVE FIX - Handles Type Mismatch
-- ============================================
-- This fixes BOTH tables to use INTEGER types for guest IDs

-- Step 1: Check current state
SELECT 'Current guests.id type:' as info;
SELECT data_type FROM information_schema.columns
WHERE table_name = 'guests' AND column_name = 'id';

SELECT 'Current contributions.guest_id type:' as info;
SELECT data_type FROM information_schema.columns
WHERE table_name = 'contributions' AND column_name = 'guest_id';

-- Step 2: Drop the foreign key constraint
ALTER TABLE contributions DROP CONSTRAINT IF EXISTS contributions_guest_id_fkey;

-- Step 3: Convert contributions.guest_id to INTEGER
-- (This assumes the column is empty or has numeric values)
ALTER TABLE contributions
ALTER COLUMN guest_id TYPE INTEGER USING guest_id::integer;

-- Step 4: Drop and recreate guests.id column as INTEGER with auto-increment
ALTER TABLE guests DROP COLUMN id CASCADE;
ALTER TABLE guests ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Step 5: Recreate the foreign key constraint (now both columns are INTEGER)
ALTER TABLE contributions
ADD CONSTRAINT contributions_guest_id_fkey
FOREIGN KEY (guest_id)
REFERENCES guests(id)
ON DELETE SET NULL;

-- Step 6: Verify the fix
SELECT 'Verification - guests.id:' as info;
SELECT column_name, data_type, column_default, is_nullable
FROM information_schema.columns
WHERE table_name = 'guests' AND column_name = 'id';

SELECT 'Verification - contributions.guest_id:' as info;
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'contributions' AND column_name = 'guest_id';

-- Success message
SELECT '✅ Fix completed! Both tables now use INTEGER for guest IDs.' as status;
