-- ============================================
-- FINAL FIX - Handles Foreign Key Constraints
-- ============================================
-- This fixes the guests table id column while preserving relationships

-- Step 1: Check if there's any data in guests table
SELECT COUNT(*) as guest_count FROM guests;

-- Step 2: Drop the foreign key constraint temporarily
ALTER TABLE contributions DROP CONSTRAINT IF EXISTS contributions_guest_id_fkey;

-- Step 3: Drop the old id column and recreate it
ALTER TABLE guests DROP COLUMN id CASCADE;

-- Step 4: Add new id column with auto-increment
ALTER TABLE guests ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Step 5: Recreate the foreign key constraint
ALTER TABLE contributions
ADD CONSTRAINT contributions_guest_id_fkey
FOREIGN KEY (guest_id)
REFERENCES guests(id)
ON DELETE SET NULL;

-- Step 6: Verify it worked
SELECT
    column_name,
    data_type,
    column_default,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'guests'
AND column_name = 'id';

-- Success message
SELECT 'Fix completed successfully! You can now add guests.' as status;
