-- SQL script to fix the guests table in Supabase
-- This will enable auto-increment for the id column

-- Make the id column auto-increment (identity column)
ALTER TABLE guests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Verify the change
SELECT column_name, column_default, is_nullable, data_type
FROM information_schema.columns
WHERE table_name = 'guests' AND column_name = 'id';
