-- ============================================
-- SUPABASE DATABASE FIX FOR WEDDING REGISTRY
-- ============================================
-- This SQL script fixes the guests table to enable auto-increment IDs
-- Run this in your Supabase SQL Editor

-- Step 1: Check current guests table structure
SELECT
    column_name,
    data_type,
    column_default,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'guests'
  AND column_name = 'id';

-- Step 2: Make the id column auto-increment (IDENTITY)
-- This is the main fix - it allows guests to be added without specifying IDs
ALTER TABLE guests
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Step 3: Verify the fix worked
SELECT
    column_name,
    data_type,
    column_default,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'guests'
  AND column_name = 'id';

-- Step 4: Test by inserting a sample guest (optional - you can delete this after)
-- Uncomment the lines below to test:
/*
INSERT INTO guests (
    name,
    email,
    phone,
    guest_code,
    invitation_type,
    guest_count,
    dietary_restrictions,
    notes,
    rsvp_status,
    has_accessed,
    total_contributed,
    contributions_count,
    date_added
) VALUES (
    'Test Guest',
    'test@example.com',
    '1234567890',
    'TEST123',
    'individual',
    1,
    '',
    'Test guest - can be deleted',
    'pending',
    false,
    0,
    0,
    NOW()
) RETURNING *;
*/

-- ============================================
-- SUCCESS!
-- ============================================
-- After running this script:
-- 1. Go back to your admin panel
-- 2. Try adding a guest
-- 3. It should work now!
-- ============================================
