-- ============================================
-- CORRECTED SUPABASE FIX FOR GUESTS TABLE
-- ============================================

-- First, check what type the id column currently is
SELECT
    column_name,
    data_type,
    column_default,
    character_maximum_length
FROM information_schema.columns
WHERE table_name = 'guests' AND column_name = 'id';

-- Option 1: If id is VARCHAR/TEXT, we need to convert it
-- WARNING: This will only work if the table is empty or has numeric IDs

-- Step 1: Drop the existing default (if any)
ALTER TABLE guests ALTER COLUMN id DROP DEFAULT;

-- Step 2: Convert the column to INTEGER type
ALTER TABLE guests ALTER COLUMN id TYPE INTEGER USING id::integer;

-- Step 3: Now add the IDENTITY generation
ALTER TABLE guests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Verify the fix
SELECT
    column_name,
    data_type,
    column_default
FROM information_schema.columns
WHERE table_name = 'guests' AND column_name = 'id';

-- ============================================
-- ALTERNATIVE FIX (if the table has data):
-- ============================================
-- If the above fails because you have existing guests with non-numeric IDs,
-- uncomment and run this instead:

/*
-- Rename the old id column
ALTER TABLE guests RENAME COLUMN id TO old_id;

-- Add new integer id column with auto-increment
ALTER TABLE guests ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY;

-- Update existing rows (if any) to have sequential IDs
UPDATE guests SET id = row_number() OVER (ORDER BY date_added);

-- Drop the old id column
ALTER TABLE guests DROP COLUMN old_id;

-- Make id the primary key
ALTER TABLE guests ADD PRIMARY KEY (id);
*/
